### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by sp9dev** [achan001/Armstrong-Numbers#1]
Attempt to compile code in VS2017 Enterprise impossible due to inability to find mem.h header. After changing to memory.h, a great number of consecutive errors appear, such as "printf intendifier not found", "undefined type big", etc. Which IDE or which compiler is able to compile the code?

**Comment by achan001** [comment]
It compile ok in GCC.
Tried GCC 3.4, 4.7, and 7.1 (from Strawsberry Perl packaged GCC)

mem.h can be replaced by string.h (it is only for memmove declaration)

Undefined type big suggested big.cpp is not "included" correctly.
Printf error also related to no big (only 2 printf in arm.cpp)
